/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ID = 1;
  /** RegularExpression Id. */
  int DOLLAR = 2;
  /** RegularExpression Id. */
  int EQ = 3;
  /** RegularExpression Id. */
  int AT = 4;
  /** RegularExpression Id. */
  int AND = 5;
  /** RegularExpression Id. */
  int HASH = 6;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"id\"",
    "\"$\"",
    "\"=\"",
    "\"@\"",
    "\"&\"",
    "\"#\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
  };

}
